[package]
name = "chaingig"
version = "0.1.0"
edition = "2021"

[lib]
name = "chaingig"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[dependencies]
anchor-lang = "0.31.1"
proc-macro2 = "1.0.63"

[features]
default = []
idl-build = ["anchor-lang/idl-build"]
